# Generated by Django 4.1.1 on 2022-10-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicstudios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-price', 'product']},
        ),
    ]
