# Generated by Django 4.1.1 on 2022-11-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstudios', '0007_alter_price_options_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
