# Generated by Django 4.1.1 on 2022-11-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstudios', '0008_order_customer_paid_order_stripe_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fullfilment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
