# Generated by Django 4.1.1 on 2022-09-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
