# Generated by Django 4.1.1 on 2022-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_song_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='featured_artists',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(max_length=200),
        ),
    ]
