# Generated by Django 4.1.1 on 2022-09-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_featured_artists_alter_song_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='picture',
            field=models.ImageField(blank=True, upload_to='singles/'),
        ),
    ]
