# Generated by Django 4.1.1 on 2022-09-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_song_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='music_audio/'),
        ),
    ]
