# Generated by Django 4.1.1 on 2022-10-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_album_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='album',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='song',
            managers=[
            ],
        ),
    ]
