# Generated by Django 4.1.1 on 2022-09-20 20:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3, 'Category type must be at least 3 characters.')])),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'Title must be at least 5 characters.')])),
                ('blog_textbox1', models.TextField()),
                ('blog_textbox2', models.TextField()),
                ('blog_textbox3', models.TextField()),
                ('blog_photo1', models.ImageField(blank=True, upload_to='blog_photos/')),
                ('blog_photo2', models.ImageField(blank=True, upload_to='blog_photos/')),
                ('summary', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(20, 'Please enter a summary of at least 20 characters.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
