# Generated by Django 4.1.1 on 2022-10-17 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicstudios', '0002_alter_price_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('MM', 'Mixing and Mastering Package'), ('MO', 'Mastering Only'), ('RF', 'Request a Feature'), ('RT', 'Request a Tutor'), ('N', 'Select an option')], default='N', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='cust_requests',
            field=models.TextField(max_length=500, null=True, verbose_name='Enter any specific requests here: (Leave blank if none): '),
        ),
        migrations.AlterField(
            model_name='order',
            name='music_file',
            field=models.FileField(upload_to='studio_orders/', verbose_name='Upload zipped music file: '),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicstudios.price', verbose_name='Number of stems: '),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicstudios.product', verbose_name='Package Type: '),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_track',
            field=models.CharField(max_length=200, null=True, verbose_name='Reference Track (Leave blank if none): '),
        ),
    ]
