# Generated by Django 4.1.1 on 2022-10-17 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicstudios', '0003_remove_product_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
