# Generated by Django 4.1.1 on 2022-10-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstudios', '0004_rename_product_name_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('Mixing and Mastering Package', 'Mixing and Mastering Package'), ('Mastering Only', 'Mastering Only'), ('Request a Feature', 'Request a Feature'), ('Request a Tutor', 'Request a Tutor'), ('Select an option', 'Select an option')], default='Select an option', max_length=100),
        ),
    ]
